### ISSUE TITLE
[Bug] 海豹核心目前的实现导致此插件覆盖 COC DND 的 rc 命令

### ISSUE THREAD

**Issue by MintCider** [MintCider/seal-fu#1]
详见 sealdice/sealdice-core#1106

暂时解决方案：如果发现安装此插件后，不能正常触发 `rc` 命令，可以通过 `.set coc`、`.set dnd` 重新激活对应规则解决。

**Comment by bugtower100** [comment]
这个或许可以考虑和其他日系规则插件指令格式对齐#挠头
比如剑世界是 .swr <式子> ，魔道书是 .mgr <式子> ，总之大概都是这类型的主指令（mg/sw）+其他

**Comment by bugtower100** [comment]
另外，根据经常使用dnd模块的用户反馈，这个插件里的buff和ri也有所冲突。

**Comment by MintCider** [comment]
上游已修复，如有需要，可以更新 1.5.0 最新测试版以解决此问题
