### ISSUE TITLE
【BUG】英文格式录卡指令解析失败

### ISSUE THREAD

**Issue by KomeijiRan** [MintCider/seal-fu#2]
插件版本0.2.0
核心版本1.4.6

![图片](https://github.com/user-attachments/assets/679ae0d3-eea8-4bcc-b49e-a73b67b428a9)
复制项目首页的命令后仅改动数值解析失败↑

![图片](https://github.com/user-attachments/assets/48434da4-b12a-43f3-93d7-6d9b3d0a1315)
复制项目首页命令不进行任何改动，仍然解析失败↑

**Comment by MintCider** [comment]
呃，可能是我当初写文档时疏忽了，没去验证

最终物语用的 `.st` 命令和 COC 7 是相同的，语法也一样，你遇到的这个问题有两种解决方式，要不把前面的人名去掉再重新命名

```text
.st dex=10 ins=6 mig=8 wlp=8 hp=50 hpmax=50 mp=50 mpmax=50 ip=6 ipmax=6 fp=3 z=170 im=-2 pd=11 md=8
.nn 卡珊德拉
```

要不把等号去了直接打数值

```text
.st 卡珊德拉-dex10 ins6 mig8 wlp8 hp50 hpmax50 mp50 mpmax50 ip6 ipmax6 fp3 z170 im-2 pd11 md8
.st 卡珊德拉-dex10ins6mig8wlp8hp50hpmax50mp50mpmax50ip6ipmax6fp3z170im-2pd11md8
```

有没有空格都可以。用中文属性名的话也一样。
