### ISSUE TITLE
[bug].sn 自动群名片功能没办法正常更改物防

### ISSUE THREAD

**Issue by 12015chen** [MintCider/seal-fu#3]
通过st命令录卡后，所有数据录入都是正常的。

但是通过sn命令更改的群名片PD都是0。（st show 物防可以显示物防值确实录入成功了）

**Comment by MintCider** [comment]
先更新一下插件（理论上 v0.2.0 修复了这个问题），再重新执行一下 `.st fu/fuS` （即使更新插件，不重新执行也不会刷新这个东西），看看有解决么？

另外 v0.2.0 修正了不少属性的名字，可以在 README 表格中看下，可能需要清空角色卡（`.st clr`）重设一下

**Comment by 12015chen** [comment]
> 先更新一下插件（理论上 v0.2.0 修复了这个问题），再重新执行一下 `.st fu/fuS` （即使更新插件，不重新执行也不会刷新这个东西），看看有解决么？
> 
> 另外 v0.2.0 修正了不少属性的名字，可以在 README 表格中看下，可能需要清空角色卡（`.st clr`）重设一下

没有问题了，感谢
